name: Lint JavaScript

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm

            - name: Download dependencies
              run: npm ci

            - name: Run ESLint
              run: npx run eslint src

            - name: Run Prettier
              run: npx prettier .

            - name: Run TypeScript
              run: npm run ts
